### GENERAL SETTINGS ###

# Site settings
title: Hackfest Contra a Corrupção.
description: "Sobre o 1o Hackfest Contra a Corrupção organizado pela UFCG, MPE-PB e Rede Paraíba."
analytics: #Google analytics code in the format XX-nnnnnnnn-n
baseurl: "/hf-contra-corrupcao1/" #important: start with /
url: http://analytics-ufcg.github.io
github_username:  analytics-ufcg

# Build settings
markdown: kramdown
permalink: /:categories/:title
excerpt_separator: <!--more--> #use this in posts to define how long the excerpt of the post (that is shown on the Blog page) is

colors:  #in hex code if not noted else
  primary: "#003e7c" #"#F70031"
  primary_rgb: "0,62,124" #"247,0,49" #rgb of the primary. Needed in some places for the transparency effect.
  secondary: "#003e7c" #"#33004D"
  link: "#428bca"
  link_hover: "#00d1c6"
  footer_heading: "#ffffff"
  footer_content: "#bfc9d3"


### CONTACT SETTINGS ###

# Social networks usernames. Many more available: google-plus, flickr, linkedin, etc). Shown in footer.
social:
  - title: facebook
    url: https://www.facebook.com/analytics.ufcg
  - title: twitter
    url: https://twitter.com/search?q=ufcg%20analytics&src=typd

# Postal address (add as many lines as necessary). Shown in footer and on Contact page.
address:
  - lines:
    - Laboratório Analytics
    - UFCG, Campina Grande
    - PB.
email: https://www.facebook.com/analytics.ufcg
tel: 83 2101-1365


### GENERAL DATA FOR VARIOUS LOCATIONS ###

# Members information. Shown on About page.
members:
  - name: Mark Webber
    position: CEO
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team01.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Paul Jameson
    position: Lead Designer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team02.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Laura Sommers
    position: Lead Developer
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team03.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle
  - name: Martin Blunt
    position: Marketing
    text: Lorem Ipsum is simply dummy text of the printing and typesetting industry.
    img: team04.jpg
    social:
      - title: envelope #use for email address
        url: mailto:name@domain.com
      - title: twitter
        url: http://twitter.com/handle

# Clients information. Shown on Home and About pages.
clients:
  - name: Ministério Público do Estado da Paraíba
    img: client01.png
  - name: TV Paraíba
    img: client02.png
  - name: Associação Paraibana do Ministério Público
    img: client03.png

# Short text about your company. Shown in footer on every page and also separately on Home and Contact page.
about: "Hackfest, ou hackathon, é uma maratona de desenvolvimento de projetos com tecnologia. Um grupo de pessoas que se junta para desenvolver software e hardware para algum fim e/ou se divertir. Nós somos esse tipo de pessoa :)"

# Testimonial content. Shown on Home and About page.
testimonial:
    message: "Hackfest, ou hackathon, é uma maratona de desenvolvimento de projetos com tecnologia. Um grupo de pessoas que se junta para desenvolver software e hardware para algum fim e/ou se divertir.<br>Nós somos esse tipo de pessoa :)"
    author: Lab Analytics
